In [ ]:
!pip install yfinance

[yfinance documentation](https://pypi.org/project/yfinance/)

In [ ]:
!pip install streamlit

In [19]:
!pip list | grep streamlit | grep -v grep

streamlit                                         0.65.0

In [20]:
!streamlit hello

  A new version of Streamlit is available.

  See what's new at https://discuss.streamlit.io/c/announcements

  Enter the following command to upgrade:
  $ pip install streamlit --upgrade


  Welcome to Streamlit. Check out our demo in your browser.

  Local URL: http://localhost:8501
  Network URL: http://198.18.44.139:8501

  Ready to create your own Python apps super quickly?
  Just head over to https://docs.streamlit.io

  May you create awesome apps!

image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
image/jpeg
^C
  Stopping...

In [21]:
import yfinance as yf

#define the ticker symbol
tickerSymbol = 'AAPL'
# 'MSFT'  'GOOGL'  'AAPL'

#get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

#get the historical prices for this ticker
tickerDf = tickerData.history(start='2011-6-22', end='2021-6-22')

tickerDf

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2011-06-21,9.725502,10.005584,9.680050,9.990229,493382400,0.0,0.0
2011-06-22,9.985928,10.100787,9.900552,9.907616,390583200,0.0,0.0
2011-06-23,9.794907,10.186471,9.769726,10.172344,559759200,0.0,0.0
2011-06-24,10.176644,10.231309,9.983780,10.022475,439807200,0.0,0.0
2011-06-27,10.060554,10.254339,10.050112,10.197216,339813600,0.0,0.0
...,...,...,...,...,...,...,...
2021-06-15,129.940002,130.600006,129.389999,129.639999,62746300,0.0,0.0
2021-06-16,130.369995,130.889999,128.460007,130.149994,91815000,0.0,0.0
2021-06-17,129.800003,132.550003,129.649994,131.789993,96721700,0.0,0.0
2021-06-18,130.710007,131.509995,130.240005,130.460007,108787300,0.0,0.0
2021-06-21,130.300003,132.410004,129.210007,132.300003,79576500,0.0,0.0

In [22]:
tickerData.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1980-12-12,0.100751,0.101189,0.100751,0.100751,469033600,0.0,0.0
1980-12-15,0.095933,0.095933,0.095495,0.095495,175884800,0.0,0.0
1980-12-16,0.088923,0.088923,0.088485,0.088485,105728000,0.0,0.0
1980-12-17,0.090676,0.091114,0.090676,0.090676,86441600,0.0,0.0
1980-12-18,0.093304,0.093742,0.093304,0.093304,73449600,0.0,0.0
...,...,...,...,...,...,...,...
2021-06-15,129.940002,130.600006,129.389999,129.639999,62746300,0.0,0.0
2021-06-16,130.369995,130.889999,128.460007,130.149994,91815000,0.0,0.0
2021-06-17,129.800003,132.550003,129.649994,131.789993,96721700,0.0,0.0
2021-06-18,130.710007,131.509995,130.240005,130.460007,108787300,0.0,0.0
2021-06-21,130.300003,132.410004,129.210007,132.300003,79576500,0.0,0.0